/**
 * Turn on git's own built-in funcname drivers.
 *
 * The `@@ -4,3 +4,3 @@ <context>` text on a hunk header is git guessing
 * which function the hunk is inside. Its default guess is "the last line
 * at column zero", which on an indented method finds the enclosing CLASS,
 * not the method. git ships better regexes for about two dozen languages,
 * but they are opt-in: a path only gets one if a gitattributes file maps
 * it to a driver.
 *
 * Most repos never set that up, so we supply it ourselves, per invocation,
 * via `-c core.attributesFile=…`. A repo's own `.gitattributes` still wins:
 * it is a higher-priority source than the per-user file.
 *
 * The USER's own per-user file is a different story, and the reason
 * `userHasAttributesFile()` exists. `-c` has the HIGHEST config priority,
 * so setting it does not sit under an existing `core.attributesFile` — it
 * replaces it, and it also displaces the spec default
 * (`$XDG_CONFIG_HOME/git/attributes`) that applies when the setting is
 * unset. That would silently drop every attribute the user defined
 * globally: not just funcname drivers, but textconv, merge drivers, `-text`.
 * So we inject ONLY when the user has no per-user attributes of their own.
 * Someone who has already written that file does not need our defaults and
 * must not lose theirs to them.
 *
 * MEASURED, so nobody re-derives it:
 *
 *   python   `class Widget:`        -> `def render(self):`
 *   java     `public class Widget {` -> `public void render() {`
 *
 * And the limitation, which matters because it covers this very repo:
 *
 *   **git has no TypeScript, JavaScript or Vue driver.** `diff=typescript`
 *   and `diff=javascript` are silently ignored (git does not error on an
 *   unknown driver), and borrowing java/cpp/csharp does not help either —
 *   their regexes do not match `render(): number {`. All five were tried;
 *   all five returned the same useless `export class Widget {` as the
 *   default. So .ts/.js/.vue get nothing from this file, and the honest
 *   fix for them is a real parser, not another regex.
 *
 * The file is generated rather than shipped as an asset: core is compiled
 * with plain `tsc` and bundled INTO the daemon, so a non-TS file next to
 * the source would not survive either step. A string constant does.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { execFileSync } from 'node:child_process';
import { cacheDir } from '../utils/xdg.js';

/**
 * Extension -> built-in git diff driver. Every driver named here was
 * verified to exist; git ignores unknown ones silently, which is exactly
 * how a typo in this table would become invisible. The test asserts each
 * one actually changes git's funcname output.
 */
export const DIFF_DRIVERS: ReadonlyArray<readonly [glob: string, driver: string]> = [
  ['*.ada', 'ada'],
  ['*.adb', 'ada'],
  ['*.ads', 'ada'],
  ['*.sh', 'bash'],
  ['*.bash', 'bash'],
  ['*.bib', 'bibtex'],
  ['*.c', 'cpp'],
  ['*.h', 'cpp'],
  ['*.cc', 'cpp'],
  ['*.cpp', 'cpp'],
  ['*.cxx', 'cpp'],
  ['*.hpp', 'cpp'],
  ['*.hh', 'cpp'],
  ['*.cs', 'csharp'],
  ['*.css', 'css'],
  ['*.scss', 'css'],
  ['*.dts', 'dts'],
  ['*.ex', 'elixir'],
  ['*.exs', 'elixir'],
  ['*.f', 'fortran'],
  ['*.f90', 'fortran'],
  ['*.go', 'golang'],
  ['*.html', 'html'],
  ['*.htm', 'html'],
  ['*.java', 'java'],
  ['*.kt', 'kotlin'],
  ['*.kts', 'kotlin'],
  ['*.md', 'markdown'],
  ['*.m', 'objc'],
  ['*.pas', 'pascal'],
  ['*.pl', 'perl'],
  ['*.pm', 'perl'],
  ['*.php', 'php'],
  ['*.py', 'python'],
  ['*.rb', 'ruby'],
  ['*.rs', 'rust'],
  ['*.scm', 'scheme'],
  ['*.tex', 'tex'],
];

/** The gitattributes text, one `glob diff=driver` line each. */
export function attributesText(): string {
  const header =
    '# Generated by diffstalker: turns on git\'s built-in funcname drivers.\n' +
    '# Lowest-priority attributes source — a repo\'s own .gitattributes wins.\n';
  return header + DIFF_DRIVERS.map(([glob, driver]) => `${glob} diff=${driver}`).join('\n') + '\n';
}

let cachedPath: string | null = null;
let userOwnsAttributes: boolean | null = null;

/**
 * Does the user already have per-user gitattributes? Either an explicit
 * `core.attributesFile`, or the XDG default path existing on disk.
 *
 * Memoized: this runs on the first `createGit` and the answer does not
 * change under a running daemon. A failure to ask git is treated as "yes,
 * they might" — the safe direction is to leave their config alone.
 */
export function userHasAttributesFile(): boolean {
  if (userOwnsAttributes !== null) return userOwnsAttributes;

  try {
    const configured = execFileSync('git', ['config', '--get', 'core.attributesFile'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      // Passed explicitly: under bun, execFileSync does NOT pick up mutations
      // to process.env made after startup.
      env: process.env,
    }).trim();
    if (configured !== '') {
      userOwnsAttributes = true;
      return true;
    }
  } catch (err) {
    // Exit 1 is "not set", which is the common case and not a failure.
    const code = (err as { status?: number }).status;
    if (code !== 1) {
      userOwnsAttributes = true;
      return true;
    }
  }

  const xdg = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
  userOwnsAttributes = fs.existsSync(path.join(xdg, 'git', 'attributes'));
  return userOwnsAttributes;
}

/**
 * Path to the generated attributes file, written on first use.
 *
 * Returns null when it cannot be written — a read-only or missing cache
 * dir must not stop git from running. The caller then simply omits the
 * config, which is the behaviour we had before this file existed.
 */
export function attributesFilePath(): string | null {
  if (cachedPath !== null) return cachedPath;
  // Their file, their rules. See the module comment.
  if (userHasAttributesFile()) return null;

  const target = path.join(cacheDir(), 'funcname.gitattributes');
  const text = attributesText();
  try {
    // Rewrite when the content changed (a driver added between versions)
    // rather than trusting whatever an older build left behind.
    let current: string | null = null;
    try {
      current = fs.readFileSync(target, 'utf8');
    } catch {
      current = null;
    }
    if (current !== text) {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      writeAtomic(target, text);
    }
    cachedPath = target;
    return cachedPath;
  } catch {
    // Remember the failure too: without this, a read-only cache dir means
    // every createGit call retries the whole mkdir/write dance.
    cachedPath = null;
    userOwnsAttributes = true;
    return null;
  }
}

/**
 * Write the file to a temp name and rename it into place.
 *
 * Two daemons starting together would otherwise interleave writes and hand
 * git a torn file. Unknown drivers are ignored, so a torn file is benign —
 * but rename is atomic and costs one line.
 */
function writeAtomic(target: string, text: string): void {
  const tmp = `${target}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, text, 'utf8');
  fs.renameSync(tmp, target);
}

/** Reset both memos. Tests only. */
export function resetAttributesFileCache(): void {
  cachedPath = null;
  userOwnsAttributes = null;
}
