/**
 * Turn on git's own built-in funcname drivers.
 *
 * The `@@ -4,3 +4,3 @@ <context>` text on a hunk header is git guessing
 * which function the hunk is inside. Its default guess is "the last line
 * at column zero", which on an indented method finds the enclosing CLASS,
 * not the method. git ships better regexes for about two dozen languages,
 * but they are opt-in: a path only gets one if a gitattributes file maps
 * it to a driver.
 *
 * Most repos never set that up, so we supply it ourselves, per invocation,
 * via `-c core.attributesFile=…`. This is the lowest-priority attributes
 * source git consults, so a repo's own `.gitattributes` — or the user's
 * `core.attributesFile` if they set one — still wins. We are filling in a
 * default, not overriding anyone.
 *
 * MEASURED, so nobody re-derives it:
 *
 *   python   `class Widget:`        -> `def render(self):`
 *   java     `public class Widget {` -> `public void render() {`
 *
 * And the limitation, which matters because it covers this very repo:
 *
 *   **git has no TypeScript, JavaScript or Vue driver.** `diff=typescript`
 *   and `diff=javascript` are silently ignored (git does not error on an
 *   unknown driver), and borrowing java/cpp/csharp does not help either —
 *   their regexes do not match `render(): number {`. All five were tried;
 *   all five returned the same useless `export class Widget {` as the
 *   default. So .ts/.js/.vue get nothing from this file, and the honest
 *   fix for them is a real parser, not another regex.
 *
 * The file is generated rather than shipped as an asset: core is compiled
 * with plain `tsc` and bundled INTO the daemon, so a non-TS file next to
 * the source would not survive either step. A string constant does.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { cacheDir } from '../utils/xdg.js';

/**
 * Extension -> built-in git diff driver. Every driver named here was
 * verified to exist; git ignores unknown ones silently, which is exactly
 * how a typo in this table would become invisible. The test asserts each
 * one actually changes git's funcname output.
 */
export const DIFF_DRIVERS: ReadonlyArray<readonly [glob: string, driver: string]> = [
  ['*.ada', 'ada'],
  ['*.adb', 'ada'],
  ['*.ads', 'ada'],
  ['*.sh', 'bash'],
  ['*.bash', 'bash'],
  ['*.bib', 'bibtex'],
  ['*.c', 'cpp'],
  ['*.h', 'cpp'],
  ['*.cc', 'cpp'],
  ['*.cpp', 'cpp'],
  ['*.cxx', 'cpp'],
  ['*.hpp', 'cpp'],
  ['*.hh', 'cpp'],
  ['*.cs', 'csharp'],
  ['*.css', 'css'],
  ['*.scss', 'css'],
  ['*.dts', 'dts'],
  ['*.ex', 'elixir'],
  ['*.exs', 'elixir'],
  ['*.f', 'fortran'],
  ['*.f90', 'fortran'],
  ['*.go', 'golang'],
  ['*.html', 'html'],
  ['*.htm', 'html'],
  ['*.java', 'java'],
  ['*.kt', 'kotlin'],
  ['*.kts', 'kotlin'],
  ['*.md', 'markdown'],
  ['*.m', 'objc'],
  ['*.pas', 'pascal'],
  ['*.pl', 'perl'],
  ['*.pm', 'perl'],
  ['*.php', 'php'],
  ['*.py', 'python'],
  ['*.rb', 'ruby'],
  ['*.rs', 'rust'],
  ['*.scm', 'scheme'],
  ['*.tex', 'tex'],
];

/** The gitattributes text, one `glob diff=driver` line each. */
export function attributesText(): string {
  const header =
    '# Generated by diffstalker: turns on git\'s built-in funcname drivers.\n' +
    '# Lowest-priority attributes source — a repo\'s own .gitattributes wins.\n';
  return header + DIFF_DRIVERS.map(([glob, driver]) => `${glob} diff=${driver}`).join('\n') + '\n';
}

let cachedPath: string | null = null;

/**
 * Path to the generated attributes file, written on first use.
 *
 * Returns null when it cannot be written — a read-only or missing cache
 * dir must not stop git from running. The caller then simply omits the
 * config, which is the behaviour we had before this file existed.
 */
export function attributesFilePath(): string | null {
  if (cachedPath !== null) return cachedPath;

  const target = path.join(cacheDir(), 'funcname.gitattributes');
  const text = attributesText();
  try {
    // Rewrite when the content changed (a driver added between versions)
    // rather than trusting whatever an older build left behind.
    let current: string | null = null;
    try {
      current = fs.readFileSync(target, 'utf8');
    } catch {
      current = null;
    }
    if (current !== text) {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, text, 'utf8');
    }
    cachedPath = target;
    return cachedPath;
  } catch {
    return null;
  }
}

/** Reset the memo. Tests only. */
export function resetAttributesFileCache(): void {
  cachedPath = null;
}
